### PR TITLE
iOS 9 compatible.

### PR DESCRIPTION
**Pull request by x-ray-s**
Platform: iOS 9.3.2
Error: new Uint8Array() `slice` function is undefined

### CODE REVIEW

**Comment by jchook** [comment]
Interesting, which browser?

[caniuse for TypedArrays](https://caniuse.com/#feat=typedarrays) says it should work for iOS Safari >= 4.3, and most other mobile browsers.

**Comment by x-ray-s** [comment]
Yeah, it makes me confused.I found it on caniuse.com, but it still has the error.

image

**Comment by jchook** [comment]
Oof.. I can't merge this because it demolishes performance from 10M ops/sec to only 3k ops/sec.

I will work on a performant fix

**Comment by x-ray-s** [comment]
It doesn't matter. I don't focus on this problem in deep, I think you are good at it.

**Comment by jchook** [comment]
I have a fix in #16 on the [15-ios-9](https://github.com/jchook/uuid-random/tree/15-ios-9) branch. 

Can you kindly see if that fixes the issue?

**Comment by x-ray-s** [comment]
OK, I will test it on the workday, the test device is in my company.

**Comment by jchook** [comment]
Closed in favor of #16

**Pull request closed without merging**
